name: swagger_dart_code_generator

version: 2.10.2

homepage: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
repository: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
issue_tracker: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

description: Have you been turned into a problem with writing code for Http
  requests? This package can help. It has all of the Http and model codegen
  functionality you have been looking for.

environment:
#  sdk: ^0.13.5
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  build: ^2.3.1
  path: ^1.8.2
  markdown: '>=5.0.0 <8.0.0'
  recase: ^4.1.0
  json_annotation: ^4.8.0
  universal_io: ^2.2.0
  collection: ^1.17.0
  dart_style: ^2.3.0
  code_builder: ^4.4.0
  http: ^0.13.5
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  remove_from_coverage: ^2.0.0
  test: ^1.23.1
  lints: ^2.0.1
 
